"""empty message

Revision ID: e18787764113
Revises: 0c0563ba25c5
Create Date: 2020-11-22 13:34:44.211084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e18787764113'
down_revision = '0c0563ba25c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'challenge', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'challenge', type_='foreignkey')
    op.drop_column('challenge', 'author_id')
    # ### end Alembic commands ###
